// Marvel Studios (MCU) theatrical releases, in release order, through the
// most recent Spider-Man film. Non-MCU Marvel movies (Sony's Spider-Man
// Universe, Fox's X-Men/Fantastic Four, etc.) are intentionally excluded.
// `era` is used only for a subtle color accent on cards.
const MARVEL_MOVIES = [
  { id: "iron-man", title: "Iron Man", year: 2008, era: "infinity" },
  { id: "incredible-hulk", title: "The Incredible Hulk", year: 2008, era: "infinity" },
  { id: "iron-man-2", title: "Iron Man 2", year: 2010, era: "infinity" },
  { id: "thor", title: "Thor", year: 2011, era: "infinity" },
  { id: "captain-america-first-avenger", title: "Captain America: The First Avenger", year: 2011, era: "infinity" },
  { id: "avengers", title: "The Avengers", year: 2012, era: "infinity" },
  { id: "iron-man-3", title: "Iron Man 3", year: 2013, era: "infinity" },
  { id: "thor-dark-world", title: "Thor: The Dark World", year: 2013, era: "infinity" },
  { id: "captain-america-winter-soldier", title: "Captain America: The Winter Soldier", year: 2014, era: "infinity" },
  { id: "guardians-1", title: "Guardians of the Galaxy", year: 2014, era: "infinity" },
  { id: "avengers-age-of-ultron", title: "Avengers: Age of Ultron", year: 2015, era: "infinity" },
  { id: "ant-man", title: "Ant-Man", year: 2015, era: "infinity" },
  { id: "captain-america-civil-war", title: "Captain America: Civil War", year: 2016, era: "infinity" },
  { id: "doctor-strange", title: "Doctor Strange", year: 2016, era: "infinity" },
  { id: "guardians-2", title: "Guardians of the Galaxy Vol. 2", year: 2017, era: "infinity" },
  { id: "spider-man-homecoming", title: "Spider-Man: Homecoming", year: 2017, era: "infinity" },
  { id: "thor-ragnarok", title: "Thor: Ragnarok", year: 2017, era: "infinity" },
  { id: "black-panther", title: "Black Panther", year: 2018, era: "infinity" },
  { id: "avengers-infinity-war", title: "Avengers: Infinity War", year: 2018, era: "infinity" },
  { id: "ant-man-wasp", title: "Ant-Man and the Wasp", year: 2018, era: "infinity" },
  { id: "captain-marvel", title: "Captain Marvel", year: 2019, era: "infinity" },
  { id: "avengers-endgame", title: "Avengers: Endgame", year: 2019, era: "infinity" },
  { id: "spider-man-far-from-home", title: "Spider-Man: Far From Home", year: 2019, era: "infinity" },
  { id: "black-widow", title: "Black Widow", year: 2021, era: "multiverse" },
  { id: "shang-chi", title: "Shang-Chi and the Legend of the Ten Rings", year: 2021, era: "multiverse" },
  { id: "eternals", title: "Eternals", year: 2021, era: "multiverse" },
  { id: "spider-man-no-way-home", title: "Spider-Man: No Way Home", year: 2021, era: "multiverse" },
  { id: "doctor-strange-multiverse", title: "Doctor Strange in the Multiverse of Madness", year: 2022, era: "multiverse" },
  { id: "thor-love-thunder", title: "Thor: Love and Thunder", year: 2022, era: "multiverse" },
  { id: "black-panther-wakanda-forever", title: "Black Panther: Wakanda Forever", year: 2022, era: "multiverse" },
  { id: "ant-man-quantumania", title: "Ant-Man and the Wasp: Quantumania", year: 2023, era: "multiverse" },
  { id: "guardians-3", title: "Guardians of the Galaxy Vol. 3", year: 2023, era: "multiverse" },
  { id: "the-marvels", title: "The Marvels", year: 2023, era: "multiverse" },
  { id: "deadpool-wolverine", title: "Deadpool & Wolverine", year: 2024, era: "multiverse" },
  { id: "captain-america-brave-new-world", title: "Captain America: Brave New World", year: 2025, era: "multiverse" },
  { id: "thunderbolts", title: "Thunderbolts*", year: 2025, era: "multiverse" },
  { id: "fantastic-four-first-steps", title: "Fantastic Four: First Steps", year: 2025, era: "multiverse" },
  { id: "spider-man-brand-new-day", title: "Spider-Man: Brand New Day", year: 2026, era: "multiverse" },
];
